config/routes.rb
Regevents::Application.routes.draw do

	root to: 'events#index'
	# get '/events' => 'events#index'
	# get '/events/new' => 'events#new', as: 'new_event'
	# get '/events/:id' => 'events#show', as: 'event'
	# get '/events/:id/edit' => 'events#edit', as: 'edit_event'
	# patch '/events/:id' => 'events#update'

	resources :events do
		resources :registrations
	end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  location        :string(255)
#  price           :decimal(, )
#  created_at      :datetime
#  updated_at      :datetime
#  starts_at       :datetime
#  description     :text
#  image_file_name :string(255)
#  capacity        :integer
#

class Event < ActiveRecord::Base

		has_many :registrations, dependent: :destroy
		validates :name, :location, presence: true
		validates :description, length: { minimum: 25 }
		validates :price, numericality: { greater_than_or_equal_to: 0 }
		validates :capacity, numericality: { only_integer: true, greater_than: 0}
		validates :image_file_name, allow_blank: true, format: {
			with: /\w+.(gif|jpg|png)\z/i,
			message: "must be of .gif, .jpg, or .png type"
		}


	def free?
		price.blank? || price.zero?
	end

	def self.upcoming
		where("starts_at >= ?", Time.now).order("starts_at")
	end

	def spaces_left
		capacity - registrations.size
	end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :event
  validates :name, presence: true
  validates :email, format: { with: /(\S+)@(\S+)/ }
  INFO_SOURCE_OPTIONS = [
  	'email',
  	'web',
  	'friend',
  	'other']
  validates :info_source,
  	inclusion: { in: INFO_SOURCE_OPTIONS }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.upcoming
	end
	def show
		@event = Event.find(params[:id])
	end
	def edit
		@event = Event.find(params[:id])
	end
	def update
		@event = Event.find(params[:id])
		if @event.update(event_params)
			redirect_to event_path(@event), notice: "Updated Successfully!"
		else
			render :edit
		end
	end
	def new
		@event = Event.new
	end
	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to event_path(@event), notice: "Created Successfully!"
		else
			render :new
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path , alert: "Event removed successfully!"
	end

	private 

	def event_params

		params.require(:event).
		permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def index
		@event = Event.find(params[:event_id])
		@registrations = @event.registrations
	end
	def show
		@event = Event.find(params[:event_id])
		@registration = @event.registrations.find(params[:id])
	end
	def new
		@event = Event.find(params[:event_id])
		@registration = @event.registrations.new
	end
	def create
		@event = Event.find(params[:event_id])
		@registration = @event.registrations.new(registration_params)
		if @registration.save
			redirect_to event_registrations_path(@event), notice: "Success!"
		else
			render :new
		end
	end

private
	def registration_params
		params.require(:registration).
		permit(:name, :email, :info_source)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def format_price(event)
		if event.free?
			content_tag(:strong, "Free")
		else
			number_to_currency(event.price)
		end
	end

	def image_helper(event)
		if event.image_file_name.blank?
			image_tag('cal_image.png')
		else
			image_tag(event.image_file_name)
		end
	end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/_form.html.erb
<div>
<%= form_for(@event) do |f| %>
<%= render 'shared/errors' %>
<br />
<p><%= f.label :name %><br />
	<%= f.text_field :name, autofocus: true %>
</p>
<p>
	<%= f.label :description %><br />
	<%= f.text_area :description, rows: 5, columns:25 %>
</p>
<p>
	<%= f.label :starts_at %><br />
	<%= f.datetime_select :starts_at %>
</p>
<p>
	<%= f.label :location %><br />
	<%= f.text_field :location %>
</p>
<p>
	<%= f.label :image_file_name %>
	<%= f.text_field :image_file_name,
		placeholder: "jpg, gif, or png file" %>
</p>
<p>
	<%= f.label :capacity %>
	<%= f.number_field :capacity %>
</p>

<p>
	<%= f.label :price %><br />
	<%= f.number_field :price %>
</p>
<%= f.submit "Save Event", class:"btn" %> <%= link_to "Cancel", events_path, class:"btn" %>

<% end %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>Event Listing</h1>

<% if flash[:alert] %>
Action taken:<%= flash[:alert] %>
<% end %>
<br />
This listing is generated on <%= Time.now %>. There are currently <%= pluralize(@events.size, 'event') %>.

<% @events.each do |event| %>
<article>
	<header>
		<%= image_helper(event) %>
		<h2><%= link_to event.name, event_path(event) %></h2>
		<h3><%= pluralize(event.spaces_left, "space") %></h3>
	</header>
	<p><%= truncate(event.description, length: 25, separator: ' ') %></p>
	<table>
		<tr>
			<th>Date</th>
			<td><%= event.starts_at %></td>
		</tr>
		<tr>
			<th>Location</th>
			<td><%= event.location %></td>
		</tr>
		<tr>
			<th>Price</th>
			<td><%= format_price(event) %></td>
		</tr>
	</table>
</article>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1>Event Detail</h1>
 
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<article>
	<header>
		<%= image_helper(@event) %>
		<h2><%= @event.name %></h2>
		<%= pluralize(@event.spaces_left, 'space') %>
	</header>
	<p><%= truncate(@event.description, length: 25, separator: ' ') %></p>
	<table>
		<tr>
			<th>Date</th>
			<td><%= @event.starts_at %></td>
		</tr>
		<tr>
			<th>Location</th>
			<td><%= @event.location %></td>
		</tr>
		<tr>
			<th>Price</th>
			<td><%= format_price(@event) %></td>
		</tr>
	</table>
</article>
<div>
	<%= link_to "Edit Event", edit_event_path(@event) %> | <%= link_to "Back to Index", events_path %>
<div>
	<%= link_to 'Register for the Event', new_event_registration_path(@event), class:"btn btn-info" %> 
</div>

app/views/layouts/_footer.html.erb
<footer>
	<p>
		Copyright &copy; 2013
	</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<%= link_to "regEvents", events_path, class: "brand" %>
		<ul class="nav">
			<li class="active"><%= link_to "All Events", events_path %></li>
			<li><%= link_to "Add Event", new_event_path %></li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Regevents</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- for devise configuration -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


<%= render 'layouts/header' %>

<div class="container">

<%= yield %>

<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/shared/_errors.html.erb
<div>
	<% if @event.errors.any? %>
	Please check this out: 
	<%= pluralize(@event.errors.count, 'error') %><br /><br />
	<% @event.errors.full_messages.each do |event_errors| %>
	<ul>
	<li><%= event_errors %></li>
	</ul>
	<% end %>
	<% end %>
</div>